### ISSUE TITLE
botの返信エラーについて

### ISSUE THREAD

**Issue by marim0ss** [ysk1180/ideatutorial#1]
はじめまして失礼します。
LINEbotのチュートリアル購入致しまして、チュートリアルを参考に2-12. LINEからアクセス の項目まで進めましたが、メッセージを送ってもbotが返信しなくて悩んでおります。
コントローラでどこかおかしいのかとも思っていますが、そのままコピペしているので記述ミスではないような気もしますが…
あとはruby2.5.1がリストに表示されなかったため2.5.0を使用しているのですが、やはり2.5.1にしないとダメでしょうか…？初学者で申し訳ありません。ご確認お願いします。

**Comment by ysk1180** [comment]
@marim0ss コメントありがとうございます！返信遅くなってしまい申し訳ございません。
どこかでエラーが起きていると思いますので、Herokuのログを確認いただけますでしょうか。

`heroku logs -t`
でHerokuのログが確認できます！
メッセージを送った際のログ（ログを開いた状態でメッセージを送ればメッセージを送った時のログが特定できるはずです）をこちらにコピペいただければ僕の方で確認させていただきます！

rubyのバージョンは2.5.1と2.5.0であればほとんど変わらないと思うので別の原因だと思います。

よろしくお願いします！
（今週から新しい会社での勤務が始まり、返信が少し遅くなってしまうかもしれません><
　返信いただく際は、メンション（@のあとに僕のID）をつけていただければすぐに気がつけるのでありがたいです）
